name: client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: ls && xcodebuild build -scheme LawBrowser CODE_SIGNING_ALLOWED=NO
